---

- hosts: ios
  gather_facts: false
  connection: network_cli

  vars:
    bgp_neighbor_ip: 1.1.1.1
  
  tasks:
  - name: Define Values From CSV File
    set_fact:
      loop_ip: "{{ lookup('csvfile', bgp_neighbor_ip +' file=csv_files/bgp_neighbors.csv delimiter=, col=1') }}"
      int_ip: "{{ lookup('csvfile', bgp_neighbor_ip +' file=csv_files/bgp_neighbors.csv delimiter=, col=2') }}"
      int_mask: "{{ lookup('csvfile', bgp_neighbor_ip +' file=csv_files/bgp_neighbors.csv delimiter=, col=3') }}"
      int_name: "{{ lookup('csvfile', bgp_neighbor_ip +' file=csv_files/bgp_neighbors.csv delimiter=, col=4') }}"
      local_as: "{{ lookup('csvfile', bgp_neighbor_ip +' file=csv_files/bgp_neighbors.csv delimiter=, col=5') }}"
      neighbor_as: "{{ lookup('csvfile', bgp_neighbor_ip +' file=csv_files/bgp_neighbors.csv delimiter=, col=6') }}"
      neigh_int_ip: "{{ lookup('csvfile', bgp_neighbor_ip +' file=csv_files/bgp_neighbors.csv delimiter=, col=7') }}"
    delegate_to: localhost
  
  - name: jinja template
    template:
      src: templates/bgp_neighbors.j2
      dest: configs/bgp_config.txt
    delegate_to: localhost
  
  #- name: Copy base config to Cisco router / switch
  # ios_config:
   #  src: bgp_neighbors.j2
